# permissions for end users to view goops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: goop-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: goop
    app.kubernetes.io/part-of: goop
    app.kubernetes.io/managed-by: kustomize
  name: goop-viewer-role
rules:
- apiGroups:
  - goop.example.com
  resources:
  - goops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goop.example.com
  resources:
  - goops/status
  verbs:
  - get
