# DestinationRules define policies for a specific route: tls config, circuit breaking,
# and load balancing. These features aren't needed by the go app, this is simply an example.

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.service.name | lower | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    # Istio-suggested labels
    app.kubernetes.io/name: {{ .Values.service.name | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  host: {{ (print .Values.service.name "." .Release.Namespace ".svc.cluster.local")  | quote }}
{{- if .Values.outlierDetection }}
  trafficPolicy:
    outlierDetection:
{{ toYaml .Values.outlierDetection | indent 6 }}
{{- end }}
  subsets:
    - name: {{ (print "v" .Values.version) | quote }}
      labels:
        version: {{ .Values.version | quote }}