# VirtualServices operate on L7 information, mapping routes by prefix, cookie, etc.
# VirtualServices bind to Gateways based on their selector and at least one-matching host;
# a host can be listed in only one VirtualService, but a VirtualService may designate multiple hosts.
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name | lower | quote }}
  labels:
    # Istio-suggested labels
    app.kubernetes.io/name: {{ .Values.virtualService.name | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.ingressGateway.name | quote }}
  hosts:
    - {{ .Values.virtualService.host | quote }}
  http:
    - match:
{{- range .Values.virtualService.matchPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
      route:
      - destination:
          host: {{ (print .Values.service.name "." .Release.Namespace ".svc.cluster.local") | quote }}
          subset: {{ (print "v" .Values.version) | quote }}
{{- if .Values.virtualService.retries }}
      retries:
{{ toYaml .Values.virtualService.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" .Values.overallTimeout}}
{{- else if .Values.virtualService.overallTimeout }}
      timeout: {{ .Values.virtualService.overallTimeout }}
{{- end }}