# Build the go-app docker image
# Equivalent to: docker build -t devregistry:5000/simple-go-app -f ./code/Dockerfile ./code
# TODO: the image was (and should be) "ref='devregistry:5000/simple-go-app'". But for some reason 
# kubectl cannot pull it (run kubectl describe against the pod to see how the image is weirdly labeled)
docker_build(
    ref='devregistry:5000/simple-go-app',
    context='./go_app/src',
    dockerfile='./go_app/src/Dockerfile',
    only='./') # NOTE: 'only' is evaluated relative to the context parameter.

# TODO (goal): install postgres chart

# install the yaml generate by the helm command; first arg is pathToChartDir
k8s_yaml(
    helm(
        './go_app/chart', 
        name='',
        namespace='development',
        values=['./go_app/chart/Values.yaml']
    )
)