apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingressGateway.name }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.ingressGateway.port }}
      name: {{ .Values.ingressGateway.portname }}
      protocol: {{ .Values.ingressGateway.protocol }}
    hosts:
    - {{ .Values.ingressGateway.port }}