apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "simple-webhook.acme.com"
webhooks:
  - name: "simple-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: webhook-example
        name: simple-webhook
        path: /mutate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMVENDQWhXZ0F3SUJBZ0lVSGhYNmpidzBR
        d3QvcFJTbVB2aVg5dkpCRXNZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRUxNQWtHQTFVRUJoTUNR
        VlV4RnpBVkJnTlZCQU1NRG5OcGJYQnNaUzEzWldKb2IyOXJNQjRYRFRJeQpNRGt4T1RFM01qWXhN
        Vm9YRFRJek1Ea3hPVEUzTWpZeE1Wb3dKakVMTUFrR0ExVUVCaE1DUVZVeEZ6QVZCZ05WCkJBTU1E
        bk5wYlhCc1pTMTNaV0pvYjI5ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNn
        S0MKQVFFQW5PTHgrZUE0NEhOVE9WZGtMb2kvczBHK3RxRjdZc1Eyak9yZ1ZHMW9ZOEpvTnA0Qmw5
        UStvUWY2a3JUMApuUENhdXBpdng1cmpHRXFnUW1MdzhOWlNCR0VobHA2NWU0Y2ltSGlqcHczOHpQ
        RGZOUXJCUmVPMWJONWFDTUJmCjBEZUd1dHZ1aFlBMTZHNkNRTDZFeGliQ05LYWp2V0V6VVlpUnIv
        dnQ5bGhLNHg1ZXR3bW95cW5KZUQyb3dYMXQKRUlxMTFOYVZZT0RLZUJGZUp5Y2t0aDU0QjhKYUdV
        Z1o1Z2w4R0xQSUZ6OHZRdDFiTjlINGRkMWlCYlZZNXJFVQpvQjEwRTFaUUMzYjlueGJOOGt5aS9s
        MG5yVGhmOHlYM0Fob0pQY2dYZWNtTGxvZDQ2MnBBby9KcU05TS8xYzlFCkVtV3d5UXhVMGt4SEpt
        bHBacVZHTVNFbGR3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVViSndTNWd4MDRlZFEKR2d2RDJV
        SGJvWDgvTFpFd0h3WURWUjBqQkJnd0ZvQVViSndTNWd4MDRlZFFHZ3ZEMlVIYm9YOC9MWkV3RHdZ
        RApWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWZWbm9rNWR0Ri9Q
        aTQwUDgxZ0xFCnNhRDF5blVxQTd1TnczTjBBajh3WDU5Q3NQbTUxTG15dWR0SFFzYmM1ZmRlODl0
        em5paXJ3QWUyNWsydDVjTFAKWDFPTGJSRjFnZW9VRlVad2dSVWFSc29XdGFLZWlCQWg0V0RhSytU
        UmFHcTV5NEhTSHBTT0xrS3lZNWdRa1RlcwpwNDJ6RnltNElpVHlJU24wU2VQKzZWd1dGWUhKbHVj
        Rmc2SVYvM2RRZ2s3YU1tUm9KV0oyQWFrWUMvY1hDQmlUCksxUGpxaFpDZU55VldSeW9TbDg1dTYr
        Zy9OTnUrai9yQy81bEU0RldoZEFrMkpMUjNhY0w3azU0M2w2QWxrVDEKNFI2V1ZvT1pUYnFBOHBz
        RldpbUtJaVZKZ0FMUW4xR1B6dnhLWWxkV0RiTzJEOVd4SDVJemZsYVpvUlJvK3B1bQp4Zz09Ci0t
        LS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2